const $=id=>document.getElementById(id);
const qs=s=>document.querySelector(s);
const qsa=s=>[...document.querySelectorAll(s)];
const STORAGE='system_v7_state';
let state=JSON.parse(localStorage.getItem(STORAGE)||'null')||defaultState();
let gpsWatch=null,gpsStart=0,gpsDistance=0,gpsLast=null,gpsTimer=null;
function defaultState(){return{apiKey:'',model:'gemini-2.5-flash-lite',player:null,stats:{strength:0,endurance:0,core:0,discipline:0},rank:'E',level:1,xp:0,etaWeeks:null,compliance:0,quest:null,penalty:null,logs:[],proof:{runKm:0,timerSec:0,pushup:0,squat:0,level:'Unverified'},photo:null,lastJudgement:null,monarch:false};}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));render();}
function log(msg,type='SYSTEM'){state.logs.unshift({time:new Date().toLocaleString('id-ID'),type,msg});state.logs=state.logs.slice(0,60);}
function showModal(text){$('modalContent').innerHTML=renderMarkdownLite(text);$('modal').hidden=false;}
function renderMarkdownLite(t=''){return String(t).replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>');}
function showScreen(name){qsa('.screen').forEach(s=>s.classList.remove('active'));$('screen-'+name).classList.add('active');qsa('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('headerTitle').textContent={status:'STATUS WINDOW',scan:'PHYSICAL SCAN',order:'CURRENT ORDER',penalty:'PENALTY ZONE',core:'SYSTEM CORE',notif:'NOTIFICATION MODULE',log:'SYSTEM LOG'}[name]||'SYSTEM';}
function nextOrder(){if(!state.player)return{title:'Physical Scan belum selesai.',desc:'System tidak akan membuka protocol sebelum tubuh dievaluasi.',action:'MULAI PHYSICAL SCAN',screen:'scan'};if(state.penalty?.active)return{title:'Penalty Zone aktif.',desc:'Reward, Gate, dan Trial dibekukan sampai penalty selesai.',action:'MASUK PENALTY ZONE',screen:'penalty'};if(!state.quest)return{title:'Daily Quest belum dibuat.',desc:'System Core akan menyusun quest sesuai target badan dan data scan.',action:'BUAT DAILY QUEST',screen:'order'};if(state.quest.status==='draft')return{title:'Daily Quest menunggu penerimaan.',desc:'Menolak bukan opsi. Terima perintah untuk memulai protocol.',action:'TERIMA DAILY QUEST',screen:'order'};if(state.quest.status==='active')return{title:'Daily Quest aktif.',desc:'Selesaikan Clear Condition. Reward tidak tersedia sebelum objective terpenuhi.',action:'LANJUTKAN QUEST',screen:'order'};if(state.quest.status==='cleared')return{title:'Clear Condition terpenuhi.',desc:'Reward tersedia. Ambil reward untuk mengunci progress.',action:'AMBIL REWARD',screen:'order'};return{title:'System menunggu perintah berikutnya.',desc:'Request Daily Command atau tunggu evaluasi.',action:'BUKA ORDER',screen:'order'};}
function calcScan(){const p=state.player;let strength=Math.min(100,Math.round((+p.pushup||0)*2.2+(+p.squat||0)*.35));let endurance=Math.max(1,Math.min(100,Math.round(100-(+p.run1k||15)*4)));let core=Math.min(100,Math.round((+p.plank||0)/2));let discipline=p.sleep>=8?55:p.sleep>=7?40:24;if(p.activity==='high')discipline+=15;if(p.activity==='medium')discipline+=8;state.stats={strength,endurance,core,discipline:Math.min(100,discipline)};let avg=(strength+endurance+core+discipline)/4;state.rank=avg>82?'A':avg>65?'B':avg>48?'C':avg>30?'D':'E';state.level=Math.max(1,Math.floor(avg/10));let base={ 'S-Rank Body Path':52,'Aesthetic Combat Build':28,'Lean Fighter Protocol':24,'Fat Loss Hunter Protocol':30,'Endurance Hunter Protocol':22}[p.goal]||28;state.etaWeeks=Math.max(8,Math.round(base+(100-avg)/8));}
function defaultQuestFromRules(){const p=state.player, s=state.stats;let push=Math.max(10,Math.round((+p.pushup||8)*1.3));let squat=Math.max(25,Math.round((+p.squat||20)*1.4));let plank=Math.max(60,Math.round((+p.plank||30)*1.6));let run= p.goal.includes('Endurance')?2.5:p.goal.includes('Fat Loss')?2.2:1.4;if(s.endurance<25)run=Math.min(run,1.2);return{status:'draft',name:'Weakness Correction Protocol',reason:`Goal: ${p.goal}. Quest disesuaikan dari Physical Scan.`,objectives:[{id:'pushup',label:'Push-up',target:push,unit:'reps',progress:0,proof:'set'},{id:'squat',label:'Squat',target:squat,unit:'reps',progress:0,proof:'set'},{id:'plank',label:'Plank',target:plank,unit:'detik',progress:0,proof:'timer'},{id:'run',label:'Walk/Run',target:run,unit:'km',progress:0,proof:'gps'}],deadline:new Date(new Date().setHours(23,59,0,0)).toISOString(),reward:{xp:120},generatedBy:'rules'};}
function render(){const order=nextOrder();$('orderTitle').textContent=order.title;$('orderDesc').textContent=order.desc;$('orderAction').textContent=order.action;$('rankLabel').textContent=state.rank;$('stName').textContent=state.player?.name||'Unknown';$('stLevel').textContent=state.level;$('stRank').textContent=state.rank;$('stGoal').textContent=state.player?.goal||'Belum ditentukan';$('stETA').textContent=state.etaWeeks?`${state.etaWeeks} minggu (dinamis)`:'Belum dihitung';$('stCompliance').textContent=`${state.compliance}%`;['Strength','Endurance','Core','Discipline'].forEach(k=>{let v=state.stats[k.toLowerCase()]||0;$('stat'+k).textContent=v;$('bar'+k).value=v;});$('rankPath').innerHTML=['E','D','C','B','A','S'].map(r=>`<div class="${r===state.rank?'active-rank':''}">${r}<br><small>${r===state.rank?'ACTIVE':'LOCKED'}</small></div>`).join('');renderQuest();renderPenalty();renderLog();$('apiKey').value=state.apiKey||'';$('modelName').value=state.model||'gemini-2.5-flash-lite';$('notifStatus').textContent=`Status izin: ${Notification?.permission||'tidak tersedia'}`;}
function renderQuest(){const q=state.quest;$('questName').textContent=q?.name||'Belum ada quest aktif.';$('questReason').textContent=q?.reason||'System menunggu Physical Scan.';$('acceptQuestBtn').style.display=q?.status==='draft'?'inline-block':'none';$('claimRewardBtn').style.display=q?.status==='cleared'?'inline-block':'none';$('failQuestBtn').style.display=q?.status==='active'?'inline-block':'none';$('questObjectives').innerHTML=q?.objectives?.map(o=>`<div class="objective ${o.progress>=o.target?'done':''}"><div><b>${o.label}</b><br><small>${o.progress}/${o.target} ${o.unit} • proof: ${o.proof}</small></div><button class="btn" data-clear="${o.id}">MANUAL +</button></div>`).join('')||'<p class="hint">Tidak ada quest.</p>';qsa('[data-clear]').forEach(btn=>btn.onclick=()=>manualProgress(btn.dataset.clear));}
function renderPenalty(){const p=state.penalty;$('penaltyTitle').textContent=p?.active?'Penalty aktif.':'Penalty belum aktif.';$('penaltyDesc').textContent=p?.active?p.reason:'Jika Daily Quest gagal, akses reward dan gate dibekukan.';$('penaltyObjectives').innerHTML=p?.objectives?.map(o=>`<div class="objective ${o.done?'done':''}"><div><b>${o.label}</b><br><small>${o.target}</small></div><button class="btn" data-pen="${o.id}">CLEAR</button></div>`).join('')||'';qsa('[data-pen]').forEach(b=>b.onclick=()=>{let o=state.penalty.objectives.find(x=>x.id===b.dataset.pen);o.done=true;save();});}
function renderLog(){$('logList').innerHTML=state.logs.length?state.logs.map(l=>`<div class="log-item"><b>[${l.type}]</b> ${l.time}<br>${l.msg}</div>`).join(''):'<p class="hint">Belum ada log.</p>';}
function updateObjective(id,val,verified=false){if(!state.quest)return;let o=state.quest.objectives.find(x=>x.id===id);if(!o)return;o.progress=Math.min(o.target,+(o.progress||0)+val);if(verified)state.proof.level='Verified';if(state.quest.objectives.every(x=>x.progress>=x.target)){state.quest.status='cleared';showModal('[CLEAR CONDITION TERPENUHI]\nReward tersedia. Ambil reward untuk mengunci progress.');notify('CLEAR CONDITION TERPENUHI','Reward tersedia. Ambil reward.');}save();}
function manualProgress(id){let o=state.quest?.objectives.find(x=>x.id===id);if(!o)return;let add=prompt(`Tambah progress ${o.label} (${o.unit})`, Math.ceil(o.target/4));if(add) updateObjective(id,+add,false);}
async function callGemini(mode,withPhoto=false){if(!state.apiKey)throw new Error('API key belum diisi.');const model=state.model||'gemini-2.5-flash-lite';const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(state.apiKey)}`;const system=`Kamu adalah SYSTEM Core untuk aplikasi body transformation terinspirasi mekanik quest/rank. Bahasa utama Indonesia tegas. Jangan jadi coach ramah. Jangan kompromi. Tetap aman: jangan menyuruh latihan saat cedera, jangan ekstrem, jangan diagnosis medis. Beri output sebagai SYSTEM TRANSMISSION. Untuk mode DAILY, balas JSON valid saja dengan schema: {"name":"...","reason":"...","objectives":[{"id":"pushup","label":"Push-up","target":number,"unit":"reps","proof":"set"},{"id":"squat","label":"Squat","target":number,"unit":"reps","proof":"set"},{"id":"plank","label":"Plank","target":number,"unit":"detik","proof":"timer"},{"id":"run","label":"Walk/Run","target":number,"unit":"km","proof":"gps"}],"warning":"..."}. Untuk selain DAILY, balas teks pendek, tajam, dan actionable.`;
const payload={player:state.player,stats:state.stats,rank:state.rank,level:state.level,etaWeeks:state.etaWeeks,quest:state.quest,penalty:state.penalty,proof:state.proof,logs:state.logs.slice(0,8),mode};
let parts=[{text:system+'\n\nDATA:\n'+JSON.stringify(payload,null,2)}];
if(withPhoto&&state.photo){parts.push({inline_data:{mime_type:state.photo.mime,data:state.photo.data}});parts.push({text:'Analisis visual umum untuk postur/komposisi kebugaran. Jangan diagnosis medis.'});}
const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}]})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||'Gemini error');return data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n')||'Tidak ada output.';}
async function generateDaily(){if(!state.player){showScreen('scan');return;}showModal('[SYSTEM CORE]\nMenyusun Daily Quest sesuai data tubuh...');try{let out=await callGemini('DAILY',false);let json=extractJson(out);state.quest={status:'draft',name:json.name||'Daily Quest',reason:json.reason||json.warning||'System command generated.',objectives:json.objectives||defaultQuestFromRules().objectives,deadline:new Date(new Date().setHours(23,59,0,0)).toISOString(),reward:{xp:140},generatedBy:'ai'};log('Daily Quest dibuat oleh System Core.','COMMAND');showModal(`[DAILY QUEST HAS ARRIVED]\n${state.quest.name}\n\n${state.quest.reason}\n\nRefusal tidak dikenali. Terima perintah.`);save();showScreen('order');}catch(e){state.quest=defaultQuestFromRules();log('AI gagal, Rule Engine mengambil alih: '+e.message,'FALLBACK');showModal('[SYSTEM CORE ERROR]\nAI tidak merespons. Rule Engine mengambil alih.\n\n'+e.message);save();showScreen('order');}}
function extractJson(text){let m=text.match(/```json\s*([\s\S]*?)```/)||text.match(/```\s*([\s\S]*?)```/);let raw=m?m[1]:text;let start=raw.indexOf('{'),end=raw.lastIndexOf('}');if(start>=0&&end>=0)raw=raw.slice(start,end+1);return JSON.parse(raw);}
function claimReward(){if(!state.quest||state.quest.status!=='cleared')return;let mult=state.proof.level==='System Verified'?1.3:state.proof.level==='Verified'?1:0.55;let xp=Math.round((state.quest.reward?.xp||120)*mult);state.xp+=xp;state.level=1+Math.floor(state.xp/300);state.stats.discipline=Math.min(100,state.stats.discipline+5);state.stats.strength=Math.min(100,state.stats.strength+3);state.stats.endurance=Math.min(100,state.stats.endurance+2);state.compliance=Math.min(100,state.compliance+8);if(mult>=1)state.etaWeeks=Math.max(4,(state.etaWeeks||20)-1);state.quest=null;log(`Reward diambil. EXP +${xp}. Proof: ${state.proof.level}.`,'REWARD');showModal(`[REWARD ACQUIRED]\nEXP +${xp}\nProof Level: ${state.proof.level}\nEstimasi target diperbarui.\n\nSystem Judgement singkat: Tubuh merespons eksekusi. Lanjutkan perintah berikutnya.`);notify('REWARD ACQUIRED',`EXP +${xp}. Quest cleared.`);state.proof={runKm:0,timerSec:0,pushup:0,squat:0,level:'Unverified'};save();}
function failQuest(){state.penalty={active:true,reason:'Daily Quest gagal. Kegagalan dicatat sebagai pelanggaran protocol.',objectives:[{id:'walk',label:'Walk/Run Penalty',target:'1.5 km verified GPS',done:false},{id:'plank',label:'Plank Penalty',target:'120 detik timer',done:false},{id:'log',label:'Failure acknowledgement',target:'Akui kegagalan. Tidak ada alasan.',done:false}]};state.quest=null;state.compliance=Math.max(0,state.compliance-12);state.etaWeeks=(state.etaWeeks||20)+1;log('Daily Quest gagal. Penalty Zone aktif.','FAILURE');notify('PENALTY ZONE ACTIVATED','Kegagalan telah dicatat.');showModal('[PENALTY ZONE ACTIVATED]\nReward dibekukan. Gate ditolak. Clear penalty untuk memulihkan akses System.');save();showScreen('penalty');}
function clearPenalty(){if(!state.penalty?.active)return;if(!state.penalty.objectives.every(o=>o.done)){showModal('[ACCESS DENIED]\nSemua penalty objective belum selesai.');return;}state.penalty.active=false;log('Penalty cleared. System access restored.','PENALTY');showModal('[PENALTY CLEARED]\nAkses System dipulihkan. Kegagalan tetap tercatat.');save();}
function notify(title,body){if('Notification' in window&&Notification.permission==='granted'){navigator.serviceWorker?.ready.then(reg=>reg.showNotification(title,{body,icon:'icons/icon-192.png',badge:'icons/icon-192.png'})).catch(()=>new Notification(title,{body}));}}
function haversine(a,b){const R=6371;let dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180;let x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
$('enterBtn').onclick=()=>{$('boot').style.display='none'};$('orderAction').onclick=()=>{let o=nextOrder();if(o.action==='BUAT DAILY QUEST')generateDaily();else if(o.action==='AMBIL REWARD')claimReward();else showScreen(o.screen);};qsa('.bottom-nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$('closeModal').onclick=()=>$('modal').hidden=true;
$('bodyPhoto').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('photoPreview').hidden=false;$('photoPreview').src=URL.createObjectURL(f);let data=await new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result.split(',')[1]);fr.readAsDataURL(f);});state.photo={mime:f.type,data};save();};
$('scanBtn').onclick=async()=>{state.player={name:$('name').value||'Player',age:+$('age').value||19,height:+$('height').value||0,weight:+$('weight').value||0,pushup:+$('pushup').value||0,squat:+$('squat').value||0,plank:+$('plank').value||0,run1k:+$('run1k').value||15,sleep:+$('sleep').value,activity:$('activity').value,equipment:$('equipment').value,goal:$('goal').value};calcScan();log('Physical Scan selesai. Protocol ditentukan.','SCAN');save();showScreen('status');let msg=`[SYSTEM VERDICT]\nRank awal: ${state.rank}\nGoal: ${state.player.goal}\nEstimasi route: ${state.etaWeeks} minggu jika compliance stabil di atas 85%.\n\nSystem akan menyusun Daily Quest pertama.`;if(state.photo&&state.apiKey){try{msg+='\n\n'+await callGemini('VISUAL SCAN',true);}catch(e){msg+='\n\nVisual AI gagal: '+e.message;}}showModal(msg);};
$('saveCoreBtn').onclick=()=>{state.apiKey=$('apiKey').value.trim();state.model=$('modelName').value.trim()||'gemini-2.5-flash-lite';save();showModal('[SYSTEM CORE SAVED]\nAPI key disimpan lokal di perangkat/browser ini.');};
qsa('[data-core]').forEach(btn=>btn.onclick=async()=>{let mode=btn.dataset.core; if(mode==='daily'){generateDaily();return;} showModal('[SYSTEM CORE]\nMemproses transmission...');try{let out=await callGemini(mode,mode==='route'&&!!state.photo);if(mode==='judgement')state.lastJudgement=out;if(mode==='route'&&state.etaWeeks)state.etaWeeks=Math.max(4,state.etaWeeks+(state.compliance<50?2:-1));log(`${mode.toUpperCase()} transmission received.`,'CORE');showModal(out);notify('SYSTEM TRANSMISSION',out.replace(/\s+/g,' ').slice(0,110));save();}catch(e){showModal('[SYSTEM CORE ERROR]\n'+e.message);}});
$('acceptQuestBtn').onclick=()=>{if(state.quest){state.quest.status='active';log('Daily Quest accepted.','COMMAND');showModal('[COMMAND ACCEPTED]\nDaily Quest aktif. Clear Condition wajib dipenuhi sebelum reward tersedia.');save();}};$('claimRewardBtn').onclick=claimReward;$('failQuestBtn').onclick=failQuest;$('clearPenaltyBtn').onclick=clearPenalty;
$('recordSetBtn').onclick=()=>{let reps=+$('repsInput').value||0,type=$('repsType').value;if(reps>0){state.proof[type]=(state.proof[type]||0)+reps;state.proof.level='Verified';updateObjective(type,reps,true);$('repsInput').value='';}};
$('startTimerBtn').onclick=()=>{let sec=+$('timerSeconds').value||60;let left=sec;$('timerDisplay').textContent=new Date(left*1000).toISOString().slice(14,19);let int=setInterval(()=>{left--;$('timerDisplay').textContent=new Date(Math.max(0,left)*1000).toISOString().slice(14,19);if(left<=0){clearInterval(int);state.proof.timerSec+=sec;state.proof.level='Verified';updateObjective('plank',sec,true);showModal('[TIMER VERIFIED]\nObjective timer selesai.');}},1000);};
$('startGpsBtn').onclick=()=>{if(!navigator.geolocation){showModal('GPS tidak tersedia.');return;}gpsStart=Date.now();gpsDistance=0;gpsLast=null;$('gpsDistance').textContent='0.00';gpsWatch=navigator.geolocation.watchPosition(pos=>{let cur={lat:pos.coords.latitude,lon:pos.coords.longitude};if(gpsLast){let d=haversine(gpsLast,cur); if(d<0.3)gpsDistance+=d;}gpsLast=cur;let mins=(Date.now()-gpsStart)/60000;$('gpsDistance').textContent=gpsDistance.toFixed(2);$('gpsTime').textContent=new Date((Date.now()-gpsStart)).toISOString().slice(14,19);$('gpsPace').textContent=gpsDistance>0?(mins/gpsDistance).toFixed(1)+'/km':'--';},err=>showModal('[GPS ERROR]\n'+err.message),{enableHighAccuracy:true,maximumAge:2000,timeout:10000});gpsTimer=setInterval(()=>{$('gpsTime').textContent=new Date((Date.now()-gpsStart)).toISOString().slice(14,19);},1000);};
$('stopGpsBtn').onclick=()=>{if(gpsWatch!==null)navigator.geolocation.clearWatch(gpsWatch);clearInterval(gpsTimer);state.proof.runKm=Math.max(state.proof.runKm,gpsDistance);if(gpsDistance>0.05){state.proof.level=gpsDistance>=1?'System Verified':'Verified';updateObjective('run',+gpsDistance.toFixed(2),true);showModal(`[GPS VERIFICATION]\nDistance verified: ${gpsDistance.toFixed(2)} km\nProof Level: ${state.proof.level}`);}save();};
$('enableNotifBtn').onclick=async()=>{if(!('Notification'in window)){showModal('Browser tidak mendukung notifikasi.');return;}let perm=await Notification.requestPermission();$('notifStatus').textContent='Status izin: '+perm;if(perm==='granted')notify('SYSTEM NOTIFICATION ACTIVE','System Warning siap dikirim.');};$('testNotifBtn').onclick=()=>notify('SYSTEM WARNING','Daily Quest belum selesai. Sisa waktu terus berkurang.');$('installHintBtn').onclick=()=>showModal('[INSTALL PWA]\n1. Buka web dari Chrome.\n2. Pastikan link HTTPS/GitHub Pages.\n3. Tekan menu titik tiga.\n4. Pilih Add to Home Screen / Install app.\n5. Buka dari ikon SYSTEM.\n\nCatatan: notifikasi background penuh perlu push server.');
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
